### ISSUE TITLE
Readthedocs not rendering properly

### ISSUE THREAD

**Issue by hmkhatri** [MOM6-community/MOM6-AnalysisCookbook#24]
In momentum and vorticity budget tutorials on readthedocs, some of the equations (in governing equations section) are not rendering properly.

**Comment by raphaeldussin** [comment]
@hmkhatri thanks for reporting the issue

**Comment by navidcy** [comment]
Was just about to open a new issue for this. :)

**Comment by hmkhatri** [comment]
@navidcy Thanks for the PR.
