### ISSUE TITLE
Update to reflect moving to `MOM6-community` org?

### ISSUE THREAD

**Issue by navidcy** [MOM6-community/MOM6-AnalysisCookbook#26]
https://github.com/MOM6-community/MOM6-AnalysisCookbook/blob/72e9cafec0c546f593ec6d3f87b06f785b542bff/setup.py#L12

**Comment by navidcy** [comment]
probably like the above there are refs to `raphaeldussin` elsewhere?

**Comment by raphaeldussin** [comment]
solved by #28
